# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

version: 2

jobs:

  build_linux_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run: |
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          ./.circleci/run_docker_build.sh
  check_linux_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_"
      - UPLOAD_PACKAGES: "False"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run: |
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          ./recipe/prepare-check.sh
          ./.circleci/run_docker_build.sh
  coverage_linux_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_"
      - UPLOAD_PACKAGES: "False"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run: |
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          ./recipe/prepare-coverage.sh
          ./.circleci/run_docker_build.sh
  valgrind_linux_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_"
      - UPLOAD_PACKAGES: "False"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run: |
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          ./recipe/prepare-valgrind.sh
          ./.circleci/run_docker_build.sh
  benchmark_linux_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_"
      - UPLOAD_PACKAGES: "False"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run: |
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          ./recipe/prepare-benchmark.sh
          ./.circleci/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:

      - build_linux_
      - check_linux_
      - coverage_linux_
      - valgrind_linux_
      - benchmark_linux_
